package pocketplanets.buildings;

import java.util.Random;

import pocketplanets.Resource;

public class ExtractorBuilding extends Building{



    // Type of resource generated by extractor 
    public Resource resource;
    
    private int maxHeldResource = 99;

    private int productionRate;

    private int resourceGenerationMax;
    private int resourceGenerationMin;

    public ExtractorBuilding(int size, Resource resource, int resourceMax, int resourceMin, String resourceType, int resourceId) {
        resource = new Resource(resourceType, resourceId, 0);

        if(resourceMax <= maxHeldResource && resourceMax > 1){
            this.resourceGenerationMax = resourceMax;
        }
        else{
            this.resourceGenerationMax = 99;
        }

        if(resourceMin > 0 && resourceMin < resourceMax){
            this.resourceGenerationMin = resourceMin;
        }
        else{
            this.resourceGenerationMin = 1;
        }
        
        generateResource(resourceGenerationMax, resourceGenerationMin);
    }

    public int generateResource(int max, int min){
        
        Random rand = new Random();
        resource.setAmount(rand.nextInt(max - min + 1) + min);
        return resource.getAmount();
    }
}
