package pocketplanets.buildings;

import java.util.Random;

import pocketplanets.Resource;

public class ExtractorBuilding extends Building{



    // Type of resource generated by extractor 
    public Resource resource;
    
    private int maxHeldResource = 99;

    private int productionRate;

    private int resourceGenerationMax = 5;
    private int resourceGenerationMin = 1;

    public ExtractorBuilding(int size, Resource resource, String resourceType, int resourceId) {
        resource = new Resource(resourceType, resourceId, 0);
        generateResource(resourceGenerationMax, resourceGenerationMin);
    }

    @Override
    public void Update(double deltaTime){
        if(resource.getAmount() < maxHeldResource){
            generateResource(resourceGenerationMax, resourceGenerationMin);
        }
    }

    /**
     * Generates resources 
     * 
     * @param max
     * @param min
     * @return
     */
    public int generateResource(int max, int min){
        
        Random rand = new Random();
        resource.setAmount(resource.getAmount() + (rand.nextInt(max - min + 1) + min));
        return resource.getAmount();
    }
}
